/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supernaut.redes2.carrito;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.net.InetAddress;
import java.net.Socket;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JLabel;
import javax.swing.JScrollPane;

/**
 *
 * @author supernaut
 */
public class CliCarrito extends javax.swing.JFrame {

    static final public boolean CARRITO = true;
    static final public boolean CATALOGO = false;
    static final private int PTO = 9090;
    private boolean paso;
    private Map<Integer, Producto> inventario;
    private Map<Integer, Short> orden;
    private ObjectInputStream objIn;
    private Socket cliente;

    /**
     * Creates new form CliCarritoGUI
     */
    public CliCarrito() throws IOException, ClassNotFoundException {
        cliente = new Socket(InetAddress.getByName("localhost"), PTO);
        objIn = new ObjectInputStream(cliente.getInputStream());
        inventario = (Map<Integer, Producto>) objIn.readObject();
        orden = new HashMap<>();
        paso = CATALOGO;
        initComponents();
        volver.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        continuar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        scrollPnl = new javax.swing.JScrollPane(new Galeria(this));
        encabezado = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        continuar.setText("continuar");
        continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                continuarActionPerformed(evt);
            }
        });

        volver.setText("volver");
        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });

        encabezado.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        encabezado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        encabezado.setText(paso == CATALOGO ? "catálogo" : "carrito");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(volver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(continuar))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(encabezado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(scrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(encabezado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(scrollPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 656, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(continuar)
                    .addComponent(volver)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private String enviaOrden() {
        ObjectOutputStream objOut;
        boolean exito;
        float total;
        try {
            // envía orden
            objOut = new ObjectOutputStream(cliente.getOutputStream());
            objOut.writeObject(orden);
            objOut.flush();
            // lee recibo
            exito = objIn.readBoolean();
            total = objIn.readFloat();
            return exito ? "total: $" + total :
                    "no hay suficientes unidades";
        } catch (IOException ex) {
            Logger.getLogger(CliCarrito.class.getName()).log(Level.SEVERE, null, ex);
            return "ha ocurrido un error";
        }
    }
    
    private void continuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_continuarActionPerformed
        JDialog dialogo;
        
        if(paso == CARRITO) {
            encabezado.setText("catálogo"); paso = CATALOGO;
            scrollPnl.setViewportView(new Galeria(this));
            volver.setEnabled(false);
            this.invalidate();
            this.validate();
            this.repaint();
            dialogo = new JDialog(this, "Compra realizada");
            dialogo.setContentPane(new JLabel(enviaOrden()));
            dialogo.setSize(100, 250);
            dialogo.setVisible(true);
        } else {
            encabezado.setText("carrito"); paso = CARRITO;
            scrollPnl.setViewportView(new Galeria(this, orden));
            volver.setEnabled(true);
            this.invalidate();
            this.validate();
            this.repaint();
        }
    }//GEN-LAST:event_continuarActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        if(paso == CARRITO) {
            encabezado.setText("catálogo");  paso = CATALOGO;
            scrollPnl.setViewportView(new Galeria(this));
            volver.setEnabled(false);
            this.invalidate();
            this.validate();
            this.repaint();
        }
    }//GEN-LAST:event_volverActionPerformed

    public boolean getPaso() {
        return paso;
    }

    public Map<Integer, Producto> getInventario() {
        return inventario;
    }

    public Map<Integer, Short> getOrden() {
        return orden;
    }                   

    void cambiaOrden(int hash, int cantidad) {
        if(orden.containsKey(hash))
            orden.replace(hash, (short) cantidad);
        else
            orden.put(hash, (short) cantidad);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CliCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CliCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CliCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CliCarrito.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new CliCarrito().setVisible(true);
                } catch (IOException | ClassNotFoundException ex) {
                    Logger.getLogger(CliCarrito.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton continuar;
    private javax.swing.JLabel encabezado;
    private transient javax.swing.JScrollPane scrollPnl;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

}
